language: python
python:
  - 3.7
services:
  - docker

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov
  - export CODECOV_TOKEN="82325faf-9124-41ce-b3a0-2f524ed31455"

script: 
  - ./rebuild_all.sh
  - docker-compose run testflask

after_success:
  - codecov