language: python
python:
- 3.7
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- tree
- python --version
- pip install -U pip
- pip install -U pytest
- pip install -U pytest-cov
- CODECOV_TOKEN="82325faf-9124-41ce-b3a0-2f524ed31455"
script:
- "./rebuild_test.sh"
- docker-compose run --rm testflask bash -c 'pytest --cov=./'
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
